version: '3.3'
services:
  # frontend:
  #   image: test-frontend
  #   build:
  #     context: ..
  #     dockerfile: ./local-dev/Dockerfile.frontend
  #   volumes:
  #     - ../frontend:/app
  #   ports:
  #     - 3000:3000
  
  backend:
    image: test-backend
    build:
      context: ..
      dockerfile: ./local-dev/Dockerfile.backend
    volumes:
      - ../backend:/app
    ports:
      - 3001:3001

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/