# base image
FROM node:14-alpine
RUN npm config set strict-ssl false

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ../backend/ /app

WORKDIR /app

RUN npm install
EXPOSE 3001

WORKDIR /app

# start app
CMD ["node", "server.js"]